name: weka
base: core22
version: '3.8.6'
summary: The workbench for machine learning
license: GPL-3.0
description: |
  Weka is free machine learning software provided by the University of Waikato, New Zealand.
  It is a cross platform framework that enables a wide variety of statistical modelling and deep learning.
  One of the major features of Weka is a high quality GUI to enable generating and evaluating models without having to write a single line of code.
  This build is unofficially provided to provide a convienient installation format via Snapcraft.
  Official builds may be downloaded at https://www.cs.waikato.ac.nz/ml/weka/
grade: stable
confinement: strict
architectures:
  - build-on: amd64
compression: lzo

parts:
  weka:
    plugin: maven
    source: https://github.com/Waikato/weka-3.8.git
    source-type: git
    source-commit: d49c085b51d93d5e26ca929fa763b3f684bf91eb
    source-subdir: weka
    build-packages:
      - maven
      - default-jdk
    stage-packages:
      - default-jre
    maven-parameters:
      - -DskipTests=true
    build-environment:
      - JAVA_HOME: '/usr/lib/jvm/java-1.11.0-openjdk-amd64/'
    override-prime: |
      craftctl default
      rm usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs

apps:
  weka:
    command: bin/java weka.gui.GUIChooser
    environment:
      JAVA_OPTS: -Xms128m -Xmx2048m
      CLASSPATH: $SNAP/jar/*
    extensions: [gnome]
    plugs:
      - network
      - home
